#by lvlevis
stages:
  - build_image
  - push_image
 
before_script:
  - source /etc/profile 
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  - APP_VERSION=`echo $CI_BUILD_REF | cut -c1-8`
 
build_image:
  stage: build_image
  tags :
    - k8s-images
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$APP_VERSION" .
  only:
    - tags
    - master
    - /^issue-.*$/
 
push_image:
  stage: push_image
  tags :
    - k8s-images
  script:
    - docker push "$CI_REGISTRY_IMAGE:$APP_VERSION"
    - docker rmi "$CI_REGISTRY_IMAGE:$APP_VERSION"
  dependencies:
    - build_image
  when: manual
  only:
    - master
    - tags
    